In [42]:
import numpy as np
import pandas
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

In [43]:
file = "dataset_preprocessed.csv"
df = pandas.read_csv(file)

In [47]:
x = df.iloc[:, 3:20]

In [48]:
y1 = df[['Tier1']]
y2 = df[['Tier2']]
y3 = df[['Tier3']]
y4 = df[['Tier4']]
y5 = df[['Tier5']]
x = x.to_numpy()
y1 = np.ravel(y1.to_numpy())
y2 = np.ravel(y2.to_numpy())
y3 = np.ravel(y3.to_numpy())
y4 = np.ravel(y4.to_numpy())
y5 = np.ravel(y5.to_numpy())

sc_x = StandardScaler()
x = sc_x.fit_transform(x)

# Logistic Regression

y1

In [49]:
x_train, x_test, y1_train, y1_test = train_test_split(x,y1,test_size=0.2)
lr = LogisticRegression()
lr.fit(x_train,y1_train)
y1_pred = lr.predict(x_test)
print(confusion_matrix(y1_test,y1_pred))
print(classification_report(y1_test,y1_pred))
print(y1_pred)
print(accuracy_score(y1_test, y1_pred))

[[35  0]
 [ 3  1]]
              precision    recall  f1-score   support

           0       0.92      1.00      0.96        35
           1       1.00      0.25      0.40         4

   micro avg       0.92      0.92      0.92        39
   macro avg       0.96      0.62      0.68        39
weighted avg       0.93      0.92      0.90        39

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0]
0.9230769230769231


c:\users\akash\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


y2

In [50]:
x_train, x_test, y2_train, y2_test = train_test_split(x,y2,test_size=0.2)
lr.fit(x_train,y2_train)
y2_pred = lr.predict(x_test)
print(confusion_matrix(y2_test,y2_pred))
print(classification_report(y2_test,y2_pred))
print(y2_pred)
print(accuracy_score(y2_test, y2_pred))

[[20  4]
 [13  2]]
              precision    recall  f1-score   support

           0       0.61      0.83      0.70        24
           1       0.33      0.13      0.19        15

   micro avg       0.56      0.56      0.56        39
   macro avg       0.47      0.48      0.45        39
weighted avg       0.50      0.56      0.51        39

[0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0
 0 0]
0.5641025641025641


c:\users\akash\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


y3

In [52]:
x_train, x_test, y3_train, y3_test = train_test_split(x,y3,test_size=0.2)
lr.fit(x_train,y3_train)
y3_pred = lr.predict(x_test)
print(confusion_matrix(y3_test,y3_pred))
print(classification_report(y3_test,y3_pred))
print(y3_pred)
print(accuracy_score(y3_test, y3_pred))

[[23  0]
 [13  3]]
              precision    recall  f1-score   support

           0       0.64      1.00      0.78        23
           1       1.00      0.19      0.32        16

   micro avg       0.67      0.67      0.67        39
   macro avg       0.82      0.59      0.55        39
weighted avg       0.79      0.67      0.59        39

[0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0]
0.6666666666666666


c:\users\akash\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


y4

In [54]:
x_train, x_test, y4_train, y4_test = train_test_split(x,y4,test_size=0.2)
lr.fit(x_train,y4_train)
y4_pred = lr.predict(x_test)
print(confusion_matrix(y4_test,y4_pred))
print(classification_report(y4_test,y4_pred))
print(y4_pred)
print(accuracy_score(y4_test, y4_pred))

[[33  1]
 [ 5  0]]
              precision    recall  f1-score   support

           0       0.87      0.97      0.92        34
           1       0.00      0.00      0.00         5

   micro avg       0.85      0.85      0.85        39
   macro avg       0.43      0.49      0.46        39
weighted avg       0.76      0.85      0.80        39

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0]
0.8461538461538461


c:\users\akash\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


y5

In [55]:
x_train, x_test, y5_train, y5_test = train_test_split(x,y5,test_size=0.2)
lr.fit(x_train,y5_train)
y5_pred = lr.predict(x_test)
print(confusion_matrix(y5_test,y5_pred))
print(classification_report(y5_test,y5_pred))
print(y5_pred)
print(accuracy_score(y5_test, y5_pred))

[[35  0]
 [ 4  0]]
              precision    recall  f1-score   support

           0       0.90      1.00      0.95        35
           1       0.00      0.00      0.00         4

   micro avg       0.90      0.90      0.90        39
   macro avg       0.45      0.50      0.47        39
weighted avg       0.81      0.90      0.85        39

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0]
0.8974358974358975


c:\users\akash\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
c:\users\akash\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


# SVM

y1

y2

y3

y4

y5

# Random Forest

y1

y2

y3

y4

y5